# Generated by Django 4.0.6 on 2023-06-06 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_ordertracker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordertracker',
            name='orderId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='store.order'),
        ),
    ]
