# Generated by Django 4.0.6 on 2023-06-06 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_ordertracker_orderid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordertracker',
            name='orderId',
            field=models.IntegerField(),
        ),
    ]
